func_name: Sock_Config
func_va: '0x1d0d0d0'
func_rva: '0xd0d0'
func_size: '0x37d'
func_sig: 81 EC 18 02 00 00 A1 ?? ?? ?? ?? 33 C4 89 84 24 ?? ?? ?? ?? 53 55 56 57 68 ?? ?? ?? ?? C7 05 ?? ?? ?? ?? ?? ?? ??
  ?? E8 ?? ?? ?? ?? 83 C4 04 85 C0
