modules:
  - name: client
    module_windows: client.dll
    module_linux: client.so
    depot_windows: czeror/cl_dlls/client.dll
    depot_linux: czeror/cl_dlls/client.so
    skills:
      - name: find-vgui2_Panel-size-callsites
        expected_input:
          - ClientVGUI_Panel_Init.{platform}.yaml
        expected_output:
          - vgui2_Panel_SetSize_Const_callsite_0.{platform}.yaml
          - vgui2_Panel_SetSize_Const_callsite_1.{platform}.yaml
          - vgui2_Panel_SetSize_Const_callsite_2.{platform}.yaml
          - vgui2_Panel_SetSize_Const_callsite_3.{platform}.yaml
          - vgui2_Panel_SetSize_Const_callsite_4.{platform}.yaml
          - vgui2_Panel_SetSize_Const_callsite_5.{platform}.yaml
          - vgui2_Panel_SetSize_Const_callsite_6.{platform}.yaml
          - vgui2_Panel_SetSize_Const_callsite_7.{platform}.yaml
          - vgui2_Panel_SetSize_Const_callsite_8.{platform}.yaml
          - vgui2_Panel_SetSize_Const_callsite_9.{platform}.yaml
          - vgui2_Panel_SetMinimumSize_Const_callsite_0.{platform}.yaml
          - vgui2_Panel_SetMinimumSize_Const_callsite_1.{platform}.yaml
        expected_output_linux:
          - vgui2_Panel_SetSize_Const_callsite_10.{platform}.yaml
          - vgui2_Panel_SetSize_Const_callsite_11.{platform}.yaml
      - name: find-client-viewport-singleton
        expected_output:
          - __g_CZEROViewPort_singleton.{platform}.yaml
      - name: find-IN_Accumulate
        expected_output:
          - IN_Accumulate.{platform}.yaml
      - name: find-client-mouse-guards
        expected_input:
          - IN_Accumulate.{platform}.yaml
        expected_output:
          - iMouseInUse.{platform}.yaml
      - name: find-GetClientColor-CS
        expected_output:
          - GetClientColor.{platform}.yaml
      - name: find-CL_IsThirdPerson-decompiles
        expected_input:
          - CL_IsThirdPerson.{platform}.yaml
        expected_output:
          - g_iUser1.{platform}.yaml
          - g_iUser2.{platform}.yaml
      - name: find-GameStudioRenderer_StudioDrawModel-decompiles
        expected_input:
          - GameStudioRenderer_StudioDrawModel.{platform}.yaml
          - GameStudioRenderer_vtable.{platform}.yaml
        expected_output:
          - GameStudioRenderer_StudioDrawPlayer.{platform}.yaml
          - GameStudioRenderer_StudioSetupBones.{platform}.yaml
          - GameStudioRenderer_StudioCalcAttachments.{platform}.yaml
          - GameStudioRenderer_StudioSaveBones.{platform}.yaml
          - GameStudioRenderer_StudioMergeBones.{platform}.yaml
          - GameStudioRenderer_StudioRenderModel.{platform}.yaml
      - name: find-GameStudioRenderer_StudioRenderModel-decompiles
        expected_input:
          - GameStudioRenderer_StudioRenderModel.{platform}.yaml
          - GameStudioRenderer_vtable.{platform}.yaml
        expected_output:
          - GameStudioRenderer_StudioRenderFinal.{platform}.yaml
      - name: find-client-studio-interface
        expected_input:
          - HUD_GetStudioModelInterface.{platform}.yaml
        expected_output:
          - GameStudioRenderer_vtable.{platform}.yaml
          - GameStudioRenderer_StudioDrawModel.{platform}.yaml
          - g_pGameStudioRenderer.{platform}.yaml
      - name: find-ClientScoreInfoHandler-decompiles
        expected_input:
          - ClientScoreInfoHandler.{platform}.yaml
        expected_output:
          - g_PlayerExtraInfo_CZDS.{platform}.yaml
      - name: find-client-ScoreInfo-handler
        expected_output:
          - ClientScoreInfoHandler.{platform}.yaml
      - name: find-client-private-predecessors
        expected_output:
          - HUD_GetStudioModelInterface.{platform}.yaml
          - CL_IsThirdPerson.{platform}.yaml
      - name: find-vgui2_Panel_Init
        expected_output:
          - ClientVGUI_Panel_Init.{platform}.yaml
          - ClientVGUI_Panel_SetProportional.{platform}.yaml
          - ClientVGUI_EditablePanel_m_NavGroup.{platform}.yaml
          - ISurface_SupportsFeature.{platform}.yaml
          - IInput_GetAppModalSurface.{platform}.yaml
          - ISchemeManager_ReloadSchemes.{platform}.yaml
      - name: find-client-vgui-keyvalues
        expected_output:
          - ClientVGUI_KeyValues_vtable.{platform}.yaml
          - ClientVGUI_KeyValues_LoadFromFile.{platform}.yaml
      - name: find-client-vgui-teammenu
        expected_output:
          - ClientVGUI_LoadControlSettings.{platform}.yaml
          - ClientVGUI_RichText_SetTextA.{platform}.yaml
          - ClientVGUI_RichText_SetTextW.{platform}.yaml
          - TeamMenu_LoadMapPage.{platform}.yaml
          - ClientVGUI_Frame_Activate.{platform}.yaml
      - name: find-client-vgui-worldmap
        expected_output:
          - CClientVGUI_WorldMapPanel.{platform}.yaml
          - CWorldMap.{platform}.yaml
          - CWorldMap_PaintBackground.{platform}.yaml
          - CWorldMapMissionSelect.{platform}.yaml
          - CWorldMapMissionSelect_PaintBackground.{platform}.yaml
          - ISurface_GetScreenSize.{platform}.yaml
    symbols:
      - name: vgui2_Panel_SetSize_Const_callsite_0
        category: patch
      - name: vgui2_Panel_SetSize_Const_callsite_1
        category: patch
      - name: vgui2_Panel_SetSize_Const_callsite_2
        category: patch
      - name: vgui2_Panel_SetSize_Const_callsite_3
        category: patch
      - name: vgui2_Panel_SetSize_Const_callsite_4
        category: patch
      - name: vgui2_Panel_SetSize_Const_callsite_5
        category: patch
      - name: vgui2_Panel_SetSize_Const_callsite_6
        category: patch
      - name: vgui2_Panel_SetSize_Const_callsite_7
        category: patch
      - name: vgui2_Panel_SetSize_Const_callsite_8
        category: patch
      - name: vgui2_Panel_SetSize_Const_callsite_9
        category: patch
      - name: vgui2_Panel_SetMinimumSize_Const_callsite_0
        category: patch
      - name: vgui2_Panel_SetMinimumSize_Const_callsite_1
        category: patch
      - name: vgui2_Panel_SetSize_Const_callsite_10
        category: patch
        platform: linux
      - name: vgui2_Panel_SetSize_Const_callsite_11
        category: patch
        platform: linux
      - name: __g_CZEROViewPort_singleton
        category: gv
        artifact: __g_CZEROViewPort_singleton.{platform}.yaml
      - name: IN_Accumulate
        category: func
      - name: iMouseInUse
        category: gv
      - name: GetClientColor
        category: func
      - name: g_PlayerExtraInfo_CZDS
        category: gv
      - name: ClientScoreInfoHandler
        category: func
      - name: GameStudioRenderer_StudioSetupBones
        category: vfunc
      - name: GameStudioRenderer_StudioSaveBones
        category: vfunc
      - name: GameStudioRenderer_StudioMergeBones
        category: vfunc
      - name: GameStudioRenderer_StudioRenderModel
        category: vfunc
      - name: GameStudioRenderer_StudioRenderFinal
        category: vfunc
      - name: GameStudioRenderer_StudioCalcAttachments
        category: vfunc
      - name: GameStudioRenderer_vtable
        category: vtable
      - name: GameStudioRenderer_StudioDrawModel
        category: vfunc
      - name: GameStudioRenderer_StudioDrawPlayer
        category: vfunc
      - name: g_pGameStudioRenderer
        category: gv
      - name: g_iUser1
        category: gv
      - name: g_iUser2
        category: gv
      - name: HUD_GetStudioModelInterface
        category: func
      - name: CL_IsThirdPerson
        category: func
      - name: ClientVGUI_Panel_Init
        category: func
      - name: ClientVGUI_KeyValues_vtable
        category: vtable
      - name: ClientVGUI_KeyValues_LoadFromFile
        category: vfunc
      - name: ClientVGUI_LoadControlSettings
        category: func
      - name: ClientVGUI_RichText_SetTextA
        category: func
      - name: ClientVGUI_RichText_SetTextW
        category: func
      - name: TeamMenu_LoadMapPage
        category: func
      - name: ClientVGUI_Frame_Activate
        category: vfunc
      - name: CZEROViewPort
        category: struct
      - name: CClientVGUI_WorldMapPanel
        category: structmember
        struct: CZEROViewPort
        member: m_pWorldMapPanel
      - name: CWorldMap
        category: vtable
      - name: CWorldMap_PaintBackground
        category: vfunc
      - name: CWorldMapMissionSelect
        category: vtable
      - name: CWorldMapMissionSelect_PaintBackground
        category: vfunc
      - name: ISurface_GetScreenSize
        category: vfunc
      - name: vgui2::EditablePanel
        category: struct
      - name: ClientVGUI_Panel_SetProportional
        category: vfunc
      - name: ClientVGUI_EditablePanel_m_NavGroup
        category: structmember
        struct: vgui2::EditablePanel
        member: m_NavGroup
      - name: ISurface_SupportsFeature
        category: vfunc
      - name: IInput_GetAppModalSurface
        category: vfunc
      - name: ISchemeManager_ReloadSchemes
        category: vfunc
  - name: server
    module_windows: cz.dll
    module_linux: cz.so
    depot_windows: czeror/dlls/cz.dll
    depot_linux: czeror/dlls/cz.so
    skills: []
    symbols: []
