modules:
  - name: engine
    path_windows: Half-Life/hw.dll
    path_linux: Half-Life/hw.so
    skills: []
    symbols: []
  - name: client
    path_windows: Half-Life/valve/cl_dlls/client.dll
    path_linux: Half-Life/valve/cl_dlls/client.so
    skills: []
    symbols: []
  - name: gameui
    path_windows: Half-Life/valve/cl_dlls/gameui.dll
    path_linux: Half-Life/valve/cl_dlls/gameui.so
    skills: []
    symbols: []
  - name: server
    path_windows: Half-Life/valve/dlls/mp.dll
    path_linux: Half-Life/valve/dlls/mp.so
    skills: []
    symbols: []
