modules:
  - name: engine
    module_windows: hw.dll
    skills:
      - name: find-R_RenderView
        expected_output:
          - R_RenderView.{platform}.yaml
      - name: find-SV_SendServerinfo
        expected_output:
          - SV_SendServerinfo.{platform}.yaml
      - name: find-build_number
        expected_output:
          - build_number.{platform}.yaml
        expected_input:
          - SV_SendServerinfo.{platform}.yaml
      - name: find-Sys_Error
        expected_output:
          - Sys_Error.{platform}.yaml
    symbols:
      - name: R_RenderView
        category: func
      - name: SV_SendServerinfo
        category: func
      - name: build_number
        category: func
      - name: Sys_Error
        category: func
