modules:
  - name: engine
    module_windows: hw.dll
    skills:
      - name: find-CL_CreateVisibleEntity-decompiles
        expected_input:
          - CL_CreateVisibleEntity.{platform}.yaml
        expected_output:
          - cl_numvisedicts.{platform}.yaml
          - cl_visedicts.{platform}.yaml
      - name: find-R_StudioCheckBBox
        expected_output:
          - R_StudioCheckBBox.{platform}.yaml
      - name: find-R_StudioCheckBBox-decompiles
        expected_input:
          - R_StudioCheckBBox.{platform}.yaml
        expected_output:
          - R_CullBox.{platform}.yaml
      - name: find-CL_Parse_SetView
        expected_input:
          - cl_parsefuncs.{platform}.yaml
        expected_output:
          - CL_Parse_SetView.{platform}.yaml
      - name: find-CL_Parse_SetView-decompiles
        expected_input:
          - CL_Parse_SetView.{platform}.yaml
        expected_output:
          - cl_viewentity.{platform}.yaml
      - name: find-CL_CreateVisibleEntity
        expected_input:
          - cl_enginefuncs.{platform}.yaml
        expected_output:
          - CL_CreateVisibleEntity.{platform}.yaml
      - name: find-VGui_ViewportPaintBackground
        expected_input:
          - cl_enginefuncs.{platform}.yaml
        expected_output:
          - VGui_ViewportPaintBackground.{platform}.yaml
      - name: find-VGui_ViewportPaintBackground-decompiles
        expected_input:
          - VGui_ViewportPaintBackground.{platform}.yaml
        expected_output:
          - V_RenderView.{platform}.yaml
      - name: find-CL_RegisterResources
        expected_output:
          - CL_RegisterResources.{platform}.yaml
      - name: find-CL_ReallocateDynamicData
        expected_output:
          - CL_ReallocateDynamicData.{platform}.yaml
      - name: find-CL_InitTEnts-studio-decompiles
        expected_input:
          - CL_InitTEnts.{platform}.yaml
        expected_output:
          - cl_sprite_shell.{platform}.yaml
      - name: find-R_StudioMergeBones-decompiles
        expected_input:
          - R_StudioMergeBones.{platform}.yaml
        expected_output:
          - cached_numbones.{platform}.yaml
          - cached_bonename.{platform}.yaml
      - name: find-R_StudioSaveBones
        expected_input:
          - cached_numbones.{platform}.yaml
          - cached_bonename.{platform}.yaml
          - R_StudioMergeBones.{platform}.yaml
          - R_StudioDrawPlayerBody.{platform}.yaml
          - R_StudioDrawPlayer.{platform}.yaml
          - R_StudioDrawModel.{platform}.yaml
          - R_StudioSetupBones.{platform}.yaml
          - R_StudioCalcAttachments.{platform}.yaml
        expected_output:
          - R_StudioSaveBones.{platform}.yaml
      - name: find-R_StudioDrawPlayerBody-decompiles
        expected_input:
          - R_StudioDrawPlayerBody.{platform}.yaml
        expected_output:
          - R_StudioMergeBones.{platform}.yaml
      - name: find-R_StudioDrawPlayer-body
        expected_input:
          - R_StudioDrawPlayer.{platform}.yaml
        expected_output:
          - R_StudioDrawPlayerBody.{platform}.yaml
      - name: find-R_StudioRenderModel-decompiles
        expected_input:
          - R_StudioRenderModel.{platform}.yaml
        expected_output:
          - R_StudioRenderFinal.{platform}.yaml
      - name: find-R_StudioRenderModel
        expected_input:
          - cl_sprite_shell.{platform}.yaml
          - g_ChromeOrigin.{platform}.yaml
          - R_StudioDrawModel.{platform}.yaml
          - R_StudioDrawPlayer.{platform}.yaml
          - R_StudioSetupBones.{platform}.yaml
          - R_StudioCalcAttachments.{platform}.yaml
        expected_output:
          - R_StudioRenderModel.{platform}.yaml
      - name: find-R_DrawTEntitiesOnList-decompiles
        expected_input:
          - R_DrawTEntitiesOnList.{platform}.yaml
        expected_output:
          - cl_parsecount.{platform}.yaml
          - size_of_frame.{platform}.yaml
      - name: find-R_DrawTEntitiesOnList
        expected_output:
          - R_DrawTEntitiesOnList.{platform}.yaml
      - name: find-R_StudioSetupBones
        expected_output:
          - R_StudioSetupBones.{platform}.yaml
      - name: find-R_StudioCalcAttachments
        expected_input:
          - R_StudioDrawModel.{platform}.yaml
        expected_output:
          - R_StudioCalcAttachments.{platform}.yaml
      - name: find-R_NewMap
        expected_output:
          - R_NewMap.{platform}.yaml
      - name: find-Mod_FindName
        expected_output:
          - Mod_FindName.{platform}.yaml
      - name: find-CL_InitTEnts
        expected_output:
          - CL_InitTEnts.{platform}.yaml
      - name: find-CL_ReallocateDynamicData-decompiles
        expected_input:
          - CL_ReallocateDynamicData.{platform}.yaml
        expected_output:
          - cl_max_edicts.{platform}.yaml
          - cl_entities.{platform}.yaml
          - cl_frames.{platform}.yaml
      - name: find-Mod_FindName-decompiles
        expected_input:
          - Mod_FindName.{platform}.yaml
        expected_output:
          - mod_known.{platform}.yaml
          - mod_numknown.{platform}.yaml
      - name: find-CL_InitTEnts-calls
        platform: windows
        expected_input:
          - CL_InitTEnts.{platform}.yaml
        expected_output:
          - CL_TempEntInit.{platform}.yaml
      - name: find-CL_TempEntInit-decompiles
        platform: windows
        expected_input:
          - CL_TempEntInit.{platform}.yaml
        expected_output:
          - gTempEnts.{platform}.yaml
      - name: find-R_NewMap-decompiles
        expected_input:
          - R_NewMap.{platform}.yaml
        expected_output:
          - r_worldentity.{platform}.yaml
          - cl_worldmodel.{platform}.yaml
      - name: find-R_RenderView
        expected_output:
          - R_RenderView.{platform}.yaml
      - name: find-SV_SendServerinfo
        expected_output:
          - SV_SendServerinfo.{platform}.yaml
      - name: find-build_number
        expected_output:
          - build_number.{platform}.yaml
        expected_input:
          - SV_SendServerinfo.{platform}.yaml
      - name: find-Sys_Error
        expected_output:
          - Sys_Error.{platform}.yaml
      - name: find-Sys_InitMemory
        expected_output:
          - Sys_InitMemory.{platform}.yaml
      - name: find-Sys_InitMemory_HeapLimitPatches
        expected_input:
          - Sys_InitMemory.{platform}.yaml
        expected_output:
          - Sys_InitMemory_HeapLimitPatches_0.{platform}.yaml
          - Sys_InitMemory_HeapLimitPatches_1.{platform}.yaml
          - Sys_InitMemory_HeapLimitPatches_2.{platform}.yaml
          - Sys_InitMemory_HeapLimitPatches_3.{platform}.yaml
      - name: find-S_LoadSound
        expected_output:
          - S_LoadSound.{platform}.yaml
      - name: find-Mod_LoadModel
        expected_output:
          - Mod_LoadModel.{platform}.yaml
      - name: find-Mod_LoadModel-decompiles
        expected_input:
          - Mod_LoadModel.{platform}.yaml
        expected_output:
          - FS_Open.{platform}.yaml
      - name: find-S_LoadSound_to_FS_Open_callsites
        expected_input:
          - S_LoadSound.{platform}.yaml
          - FS_Open.{platform}.yaml
        expected_output:
          - S_LoadSound_to_FS_Open_callsite_0.{platform}.yaml
      - name: find-Mod_LoadModel_to_FS_Open_callsites
        expected_input:
          - Mod_LoadModel.{platform}.yaml
          - FS_Open.{platform}.yaml
        expected_output:
          - Mod_LoadModel_to_FS_Open_callsite_0.{platform}.yaml
      - name: find-ClientDLL_Init
        expected_output:
          - ClientDLL_Init.{platform}.yaml
      - name: find-ClientDLL_HudInit
        expected_output:
          - ClientDLL_HudInit.{platform}.yaml
      - name: find-CBaseUI__Initialize
        expected_output:
          - CBaseUI__Initialize.{platform}.yaml
      - name: find-CL_PrecacheResources
        expected_output:
          - CL_PrecacheResources.{platform}.yaml
      - name: find-cl_resourcesonhand
        expected_input:
          - CL_PrecacheResources.{platform}.yaml
        expected_output:
          - cl_resourcesonhand.{platform}.yaml
      - name: find-ClientDLL_HudInit-decompiles
        expected_input:
          - ClientDLL_Init.{platform}.yaml
          - ClientDLL_HudInit.{platform}.yaml
        expected_output:
          - cl_enginefuncs.{platform}.yaml
          - cl_funcs.{platform}.yaml
          - g_phClientModule.{platform}.yaml
      - name: find-CBaseUI__Initialize-decompiles
        expected_input:
          - CBaseUI__Initialize.{platform}.yaml
        expected_output:
          - g_pClientFactory.{platform}.yaml
      - name: find-DispatchDirectUserMsg
        expected_output:
          - DispatchDirectUserMsg.{platform}.yaml
      - name: find-DispatchDirectUserMsg-decompiles
        expected_input:
          - DispatchDirectUserMsg.{platform}.yaml
        expected_output:
          - gClientUserMsgs.{platform}.yaml
      - name: find-cl_parsefuncs
        expected_output:
          - cl_parsefuncs.{platform}.yaml
      - name: find-VideoMode_Create
        expected_output:
          - VideoMode_Create.{platform}.yaml
      - name: find-VideoMode_Create-decompiles
        expected_input:
          - VideoMode_Create.{platform}.yaml
        expected_output:
          - videomode.{platform}.yaml
      - name: find-NLoadBlob
        platform: windows
        expected_output:
          - NLoadBlob.{platform}.yaml
      - name: find-NLoadBlobFile
        platform: windows
        expected_input:
          - NLoadBlob.{platform}.yaml
        expected_output:
          - NLoadBlobFile.{platform}.yaml
      - name: find-Cvar_DirectSet
        expected_output:
          - Cvar_DirectSet.{platform}.yaml
      - name: find-Cvar_Set
        expected_input:
          - Cvar_DirectSet.{platform}.yaml
        expected_output:
          - Cvar_Set.{platform}.yaml
      - name: find-Cvar_Set_to_Cvar_DirectSet_callsites
        expected_input:
          - Cvar_Set.{platform}.yaml
          - Cvar_DirectSet.{platform}.yaml
        expected_output:
          - Cvar_Set_to_Cvar_DirectSet_callsite_0.{platform}.yaml
      - name: find-ClientDLL_Shutdown
        expected_input:
          - ClientDLL_Init.{platform}.yaml
        expected_output:
          - ClientDLL_Shutdown.{platform}.yaml
      - name: find-FreeBlob-legacy
        expected_input:
          - ClientDLL_Shutdown.{platform}.yaml
        expected_output:
          - FreeBlob.{platform}.yaml
      - name: find-studioapi_SetupPlayerModel
        expected_output:
          - studioapi_SetupPlayerModel.{platform}.yaml
      - name: find-R_StudioDrawPlayer
        expected_input:
          - studioapi_SetupPlayerModel.{platform}.yaml
        expected_output:
          - R_StudioDrawPlayer.{platform}.yaml
      - name: find-studioapi_GetCurrentEntity
        expected_output:
          - studioapi_GetCurrentEntity.{platform}.yaml
          - currententity.{platform}.yaml
      - name: find-studioapi_SetRenderModel
        expected_output:
          - studioapi_SetRenderModel.{platform}.yaml
          - r_model.{platform}.yaml
      - name: find-studioapi_StudioSetHeader
        expected_output:
          - studioapi_StudioSetHeader.{platform}.yaml
          - pstudiohdr.{platform}.yaml
      - name: find-studioapi_SetChromeOrigin
        expected_output:
          - studioapi_SetChromeOrigin.{platform}.yaml
          - r_origin.{platform}.yaml
          - g_ChromeOrigin.{platform}.yaml
      - name: find-R_StudioDrawModel
        expected_input:
          - R_StudioDrawPlayer.{platform}.yaml
        expected_output:
          - R_StudioDrawModel.{platform}.yaml
      - name: find-R_StudioChangePlayerModel
        platform: windows
        expected_input:
          - studioapi_SetupPlayerModel.{platform}.yaml
        expected_output:
          - R_StudioChangePlayerModel.{platform}.yaml
      - name: find-DM_PlayerState
        expected_input:
          - studioapi_SetupPlayerModel.{platform}.yaml
        expected_output:
          - DM_PlayerState.{platform}.yaml
      - name: find-Host_IsSinglePlayerGame
        expected_input:
          - studioapi_SetupPlayerModel.{platform}.yaml
        expected_output:
          - Host_IsSinglePlayerGame.{platform}.yaml
      - name: find-cl_players_model
        expected_input:
          - studioapi_SetupPlayerModel.{platform}.yaml
        expected_output:
          - cl_players_model.{platform}.yaml
      - name: find-engine
        expected_output:
          - engine.{platform}.yaml
      - name: find-studioapi_SetupPlayerModel_to_R_StudioChangePlayerModel_CallSites
        platform: windows
        expected_input:
          - studioapi_SetupPlayerModel.{platform}.yaml
          - R_StudioChangePlayerModel.{platform}.yaml
        expected_output:
          - studioapi_SetupPlayerModel_to_R_StudioChangePlayerModel_callsite_0.{platform}.yaml
          - studioapi_SetupPlayerModel_to_R_StudioChangePlayerModel_callsite_1.{platform}.yaml
    symbols:
      - name: NLoadBlob
        category: func
        platform: windows
      - name: NLoadBlobFile
        category: func
        platform: windows
      - name: CL_RegisterResources
        category: func
      - name: VGui_ViewportPaintBackground
        category: func
      - name: CL_CreateVisibleEntity
        category: func
      - name: CL_Parse_SetView
        category: func
      - name: R_StudioCheckBBox
        category: func
      - name: R_CullBox
        category: func
      - name: cl_viewentity
        category: gv
      - name: cl_numvisedicts
        category: gv
      - name: cl_visedicts
        category: gv
      - name: V_RenderView
        category: func
      - name: CL_ReallocateDynamicData
        category: func
      - name: cl_sprite_shell
        category: gv
      - name: cached_numbones
        category: gv
      - name: cached_bonename
        category: gv
      - name: R_StudioSaveBones
        category: func
      - name: R_StudioMergeBones
        category: func
      - name: R_StudioDrawPlayerBody
        category: func
      - name: R_StudioRenderFinal
        category: func
      - name: R_StudioRenderModel
        category: func
      - name: cl_parsecount
        category: gv
      - name: size_of_frame
        category: scalar
      - name: R_DrawTEntitiesOnList
        category: func
      - name: R_StudioSetupBones
        category: func
      - name: R_StudioCalcAttachments
        category: func
      - name: Mod_FindName
        category: func
      - name: CL_InitTEnts
        category: func
      - name: R_NewMap
        category: func
      - name: cl_max_edicts
        category: gv
      - name: cl_entities
        category: gv
      - name: cl_frames
        category: gv
      - name: mod_known
        category: gv
      - name: mod_numknown
        category: gv
      - name: CL_TempEntInit
        category: func
        platform: windows
      - name: gTempEnts
        category: gv
      - name: r_worldentity
        category: gv
      - name: cl_worldmodel
        category: gv
      - name: R_RenderView
        category: func
      - name: SV_SendServerinfo
        category: func
      - name: build_number
        category: func
      - name: Sys_Error
        category: func
      - name: Sys_InitMemory
        category: func
      - name: Sys_InitMemory_HeapLimitPatches_0
        category: patch
      - name: Sys_InitMemory_HeapLimitPatches_1
        category: patch
      - name: Sys_InitMemory_HeapLimitPatches_2
        category: patch
      - name: Sys_InitMemory_HeapLimitPatches_3
        category: patch
      - name: S_LoadSound
        category: func
      - name: Mod_LoadModel
        category: func
      - name: FS_Open
        category: func
      - name: S_LoadSound_to_FS_Open_callsite_0
        category: patch
      - name: Mod_LoadModel_to_FS_Open_callsite_0
        category: patch
      - name: ClientDLL_Init
        category: func
      - name: ClientDLL_HudInit
        category: func
      - name: CBaseUI__Initialize
        category: func
      - name: CL_PrecacheResources
        category: func
      - name: cl_resourcesonhand
        category: gv
      - name: cl_enginefuncs
        category: gv
      - name: cl_funcs
        category: gv
      - name: g_phClientModule
        category: gv
      - name: g_pClientFactory
        category: gv
      - name: DispatchDirectUserMsg
        category: func
      - name: gClientUserMsgs
        category: gv
      - name: cl_parsefuncs
        category: gv
      - name: VideoMode_Create
        category: func
      - name: videomode
        category: gv
      - name: Cvar_DirectSet
        category: func
      - name: Cvar_Set
        category: func
      - name: Cvar_Set_to_Cvar_DirectSet_callsite_0
        category: patch
      - name: ClientDLL_Shutdown
        category: func
      - name: FreeBlob
        category: func
      - name: studioapi_SetupPlayerModel
        category: func
      - name: R_StudioDrawPlayer
        category: func
      - name: studioapi_GetCurrentEntity
        category: func
      - name: currententity
        category: gv
      - name: studioapi_SetRenderModel
        category: func
      - name: r_model
        category: gv
      - name: studioapi_StudioSetHeader
        category: func
      - name: pstudiohdr
        category: gv
      - name: studioapi_SetChromeOrigin
        category: func
      - name: r_origin
        category: gv
      - name: g_ChromeOrigin
        category: gv
      - name: R_StudioDrawModel
        category: func
      - name: R_StudioChangePlayerModel
        category: func
        platform: windows
      - name: DM_PlayerState
        category: gv
      - name: Host_IsSinglePlayerGame
        category: func
      - name: cl_players_model
        category: gv
      - name: engine
        category: gv
      - name: studioapi_SetupPlayerModel_to_R_StudioChangePlayerModel_callsite_0
        category: patch
        platform: windows
      - name: studioapi_SetupPlayerModel_to_R_StudioChangePlayerModel_callsite_1
        category: patch
        platform: windows
