modules:
  - name: engine
    module_windows: hw.dll
    module_linux: hw.so
    depot_windows: hw.dll
    depot_linux: hw.so
    skills:
      - name: find-R_RenderView
        expected_output:
          - R_RenderView.{platform}.yaml
      - name: find-SV_SendServerinfo-svencoop
        expected_output:
          - SV_SendServerinfo.{platform}.yaml
      - name: find-build_number
        expected_output:
          - build_number.{platform}.yaml
        expected_input:
          - SV_SendServerinfo.{platform}.yaml
      - name: find-Sys_Error
        expected_output:
          - Sys_Error.{platform}.yaml
      - name: find-ClientDLL_Init
        expected_output:
          - ClientDLL_Init.{platform}.yaml
      - name: find-ClientDLL_HudInit
        platform: windows
        expected_output:
          - ClientDLL_HudInit.{platform}.yaml
      - name: find-CBaseUI__Initialize
        platform: windows
        expected_output:
          - CBaseUI__Initialize.{platform}.yaml
      - name: find-ClientDLL_HudInit-decompiles
        platform: windows
        expected_input:
          - ClientDLL_Init.{platform}.yaml
          - ClientDLL_HudInit.{platform}.yaml
        expected_output:
          - cl_enginefuncs.{platform}.yaml
          - cl_funcs.{platform}.yaml
          - g_phClientModule.{platform}.yaml
      - name: find-CBaseUI__Initialize-decompiles
        platform: windows
        expected_input:
          - CBaseUI__Initialize.{platform}.yaml
        expected_output:
          - g_pClientFactory.{platform}.yaml
      - name: find-DispatchDirectUserMsg
        expected_output:
          - DispatchDirectUserMsg.{platform}.yaml
      - name: find-DispatchDirectUserMsg-decompiles
        expected_input:
          - DispatchDirectUserMsg.{platform}.yaml
        expected_output:
          - gClientUserMsgs.{platform}.yaml
      - name: find-cl_parsefuncs
        expected_output:
          - cl_parsefuncs.{platform}.yaml
      - name: find-VideoMode_Create
        expected_output:
          - VideoMode_Create.{platform}.yaml
      - name: find-VideoMode_Create-decompiles
        expected_input:
          - VideoMode_Create.{platform}.yaml
        expected_output:
          - videomode.{platform}.yaml
    symbols:
      - name: R_RenderView
        category: func
      - name: SV_SendServerinfo
        category: func
      - name: build_number
        category: func
      - name: Sys_Error
        category: func
      - name: ClientDLL_Init
        category: func
      - name: ClientDLL_HudInit
        category: func
        platform: windows
      - name: CBaseUI__Initialize
        category: func
        platform: windows
      - name: cl_enginefuncs
        category: gv
        platform: windows
      - name: cl_funcs
        category: gv
        platform: windows
      - name: g_phClientModule
        category: gv
        platform: windows
      - name: g_pClientFactory
        category: gv
        platform: windows
      - name: DispatchDirectUserMsg
        category: func
      - name: gClientUserMsgs
        category: gv
      - name: cl_parsefuncs
        category: gv
      - name: VideoMode_Create
        category: func
      - name: videomode
        category: gv
  - name: client
    module_windows: client.dll
    module_linux: client.so
    depot_windows: svencoop/cl_dlls/client.dll
    depot_linux: svencoop/cl_dlls/client.so
    skills: []
    symbols: []
  - name: gameui
    module_windows: GameUI.dll
    module_linux: gameui.so
    depot_windows: svencoop/cl_dlls/GameUI.dll
    depot_linux: svencoop/cl_dlls/gameui.so
    skills: []
    symbols: []
  - name: server
    module_windows: server.dll
    module_linux: server.so
    depot_windows: svencoop/dlls/server.dll
    depot_linux: svencoop/dlls/server.so
    skills: []
    symbols: []
