func_name: COptionsSubVideo::ApplyVidSettings(bool)
func_va: '0x738a0'
func_rva: '0x738a0'
func_size: '0x2a2'
func_sig: 55 57 56 53 81 EC ?? ?? ?? ?? 0F B6 84 24 ?? ?? ?? ?? 8B B4 24 ?? ?? ?? ?? E8 ?? ?? ?? ?? 81 C3 ?? ?? ?? ?? 88 44
  24 ?? 8B 86 ?? ?? ?? ?? 85 C0 74 ?? 8B 10 8D 7C 24 ?? BD ?? ?? ?? ?? 89 04 24 89 6C 24 ?? 89 7C 24 ?? FF 92 ?? ?? ?? ??
  8D 44 24 ?? 89 44 24 ?? 8D 44 24 ?? 89 44 24 ?? 8D 83 ?? ?? ?? ?? 89 44 24 ?? 89 3C 24 E8 ?? ?? ?? ?? 8B 44 24 ?? 89 86
  ?? ?? ?? ?? 8B 44 24 ?? 89 86 ?? ?? ?? ?? B8 ?? ?? ?? ?? 89 86 ?? ?? ?? ?? 8B 86 ?? ?? ?? ?? 85 C0 74 ?? 8B 10 B9 ?? ??
  ?? ?? BF ?? ?? ?? ?? 89 4C 24 ?? 8D 4C 24 ?? 89 4C 24 ?? 89 04 24 FF 92 ?? ?? ?? ?? 66 89 BE ?? ?? ?? ?? C6 86 ?? ?? ??
  ?? ?? 8B 86 ?? ?? ?? ?? 85 C0 74 ?? 8B 10 89 04 24 FF 92 ?? ?? ?? ?? 0F B6 C0 89 86 ?? ?? ?? ?? 8B 86 ?? ?? ?? ?? 85 C0
  74 ?? 8B 10 89 04 24 FF 92 ?? ?? ?? ?? 0F B6 C0 89 86 ?? ?? ?? ??
func_sig_allow_across_function_boundary: true
